AZURE_LOCATION: 'uksouth'
RESOURCE_NAME_PREFIX: 'apimlza'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'apimlza-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'github.com/NigelTJParker'
CICD_AGENT_TYPE: 'github'
CERT_TYPE: 'selfsigned'
